name: Publish Obsidian Plugin
"on":
  workflow_dispatch:
    inputs:
      bump:
        default: false
        description: "Bump version"
        type: boolean
        required: false
      beta:
        default: false
        description: "Publish as beta release"
        type: boolean
        required: false
  push:
    tags:
      - "*"

permissions:
  contents: write
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "${{ github.event.inputs.bump }}"
          echo "${{ github.event_name }}"
  publish:
    if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && inputs.bump == false)
    uses: lisandra-dev/reusable-workflows/.github/workflows/obsidian-plugin-publish.yaml@main
    with:
      PLUGIN_NAME: "my-plugin"
    secrets: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BETA: ${{ github.event.inputs.beta }}
  bump:
    if: ${{ github.event.inputs.bump == true }}
    uses: lisandra-dev/reusable-workflows/.github/workflows/bump.yaml@main
    with:
      PLUGIN_NAME: "my-plugin"
      BRANCH: "master"
      BETA: ${{ github.event.inputs.beta }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}