name: Publish
on: 
  workflow_call:
    inputs:
      PLUGIN_NAME:
        description: "id of your plugin"
        required: true
        type: string
      STYLE:
        description: "If you use a styles.css file, set this to true"
        required: false
        type: boolean
        default: false
    secrets:
      GH_TOKEN:
        description: "Github token"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        id: build
        run: |
          npm install
          npm run build  -- --output-dir ${{ inputs.PLUGIN_NAME }}
      - name: Get version
        id: tags
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo ${{ env. VERSION }}
          echo "## Release ${{ env. VERSION }}" >> $GITHUB_STEP_SUMMARY
      - name: Create zip
        run: |
          zip -r ${{ inputs.PLUGIN_NAME }}.zip ${{ inputs.PLUGIN_NAME }}
          echo "### Files" >> $GITHUB_STEP_SUMMARY
          ls >> $GITHUB_STEP_SUMMARY
      - name: Delete release if workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        continue-on-error: true
        run: gh release delete ${{ env.VERSION }} -R ${{ github.repository }} -y
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Create changelog
        run: |
          npx rexreplace "^.*?#+\s\[.*?\n.*?(?=\s*#+\s\[)" "_" -s -M -G -m -o "CHANGELOG.md" > CHANGELOG-LATEST.md
          cat CHANGELOG-LATEST.md >> $GITHUB_STEP_SUMMARY
      - name: Create Release with css
        if: inputs.STYLE
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          VERSION: "${{ env.VERSION }}"
        with:
          tag_name: "${{ env.VERSION }}"
          name: "${{ env.VERSION }}"
          body_path: CHANGELOG-LATEST.md
          draft: false
          prerelease: false
          token: "${{ secrets.GH_TOKEN }}"
          files: |
            ${{ inputs.PLUGIN_NAME }}.zip
            ${{ inputs.PLUGIN_NAME }}/main.js
            ${{ inputs.PLUGIN_NAME }}/manifest.json
            ${{ inputs.PLUGIN_NAME }}/styles.css
      - name: Create Release without css
        if: ${{ !inputs.STYLE }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          VERSION: "${{ env.VERSION }}"
        with:
          tag_name: "${{ env.VERSION }}"
          name: "${{ env.VERSION }}"
          body_path: CHANGELOG-LATEST.md
          draft: false
          prerelease: false
          token: "${{ secrets.GH_TOKEN }}"
          files: |
            ${{ inputs.PLUGIN_NAME }}.zip
            ${{ inputs.PLUGIN_NAME }}/main.js
            ${{ inputs.PLUGIN_NAME }}/manifest.json
        

